changelog:
  categories:
    - title: '🚀 New Features'
      labels:
        - enhancement
    - title: '🐛 Bug Fixes'
      labels:
        - bug
    - title: '🔧 Maintenance'
      labels:
        - chore
    - title: '⚠️ Breaking Changes'
      labels:
        - breaking-change
    - title: '🧹 Other Changes'
      labels:
        - '*'